CREATE TABLE ENRICO_PAIS (ID_PAIS NUMBER PRIMARY KEY,
                        NOME_PAIS VARCHAR2(30)NOT NULL);
            
CREATE TABLE ENRICO_ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                            NOME_ESTADO VARCHAR2(30) NOT NULL,
                            ID_PAIS NUMBER);
                            
                            
ALTER TABLE ENRICO_ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY
(ID_ESTADO) REFERENCES ENRICO_PAIS (ID_PAIS);